### ISSUE TITLE
Threading and ram usage

### ISSUE THREAD

**Issue by hobodrifterdavid** [ufal/udpipe#100]
Hi. This is a really neat project. I was wondering, is there support for multithreading (can process using multiple threads, that share models in ram)? (for inference, not training) This would avoiding the need to have multiple copies of the models in ram, ie when using multiple UDPipe processes, for parallelization.

I started to read the code, but didn't see any mention of threads yet. I perhaps might be able to contribute to the code at some point, if I have time.

**Comment by foxik** [comment]
The documentation https://ufal.mff.cuni.cz/udpipe/api-reference only mentions classes which are not thread-safe, namely `InputFormat` and `OutputFormat`. All other classes are thread-safe, so you can easily use the same model from multiple threads at the same time.

BTW, we use https://github.com/ufal/udpipe/blob/master/src/utils/threadsafe_stack.h to implement per-thread storage when needed -- mainly in https://github.com/ufal/udpipe/blob/master/src/model/model_morphodita_parsito.h there are "caches" for taggers and parsers, which are per-thread buffers.

BTW2, currently tagging/parsing using a single model can be done in one thread only, but we are working also on a possibility to use multiple threads for a single tagging/parsing operation.
