### ISSUE TITLE
Compatibility of Java and UDPipe

### ISSUE THREAD

**Issue by roddar92** [ufal/udpipe#104]
Dear colleagues,
I'm trying to load an English model to Model class.
But I get several exceptions:
- java.lang.UnsatisfiedLinkError: no udpipe_java in java.library.path
- java.lang.NoClassDefFoundError: Could not initialize class cz.cuni.mff.ufal.udpipe.udpipe_javaJNI

I've just downloaded udpipe library from Maven repository. 
What's wrong with my settings? What anything else (maybe .so files) should I add for completely work of UDiPipe? Who had similar problems like mine?

P.S. I'm working on Windows OS.

Thanks in advance,
Daria

**Comment by foxik** [comment]
The Maven repository package is not maintained by us; we only have the Java precompiled package as a part of the official release https://github.com/ufal/udpipe/releases . If you download the udpipe-1.2.0-bin.zip, you will find bin-win64/java containing both a .jar file and udpipe_java.dll library.

The error you are reporting is that the udpipe_java.dll was not found -- but as I not the maintainer of the Maven package, I am not sure what went wrong. Closing, but feel free to reopen if needed.

**Comment by dedekj** [comment]
Unfortunately the Maven central repository contains only the java part of udpipe. 
The rest  was uploaded only to http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-model-releases-local
See details in #12

**Comment by roddar92** [comment]
Dear colleagues,
Thanks a lot for help with CPP sources!
Where could I find a pre-trained model for UDPipe initialization in Java?

**Comment by foxik** [comment]
Do you want precompiled C++ library for Java, or pretrained models? The precompiled C++ library can be found in the official releases  https://github.com/ufal/udpipe/releases, the list of pretrained models is at http://ufal.mff.cuni.cz/udpipe#available_models.

**Comment by roddar92** [comment]
I prefer pretrained models. Does Java wrapper work with `.udpipe` models?

**Comment by foxik** [comment]
Of course, we have only one model type, which can be used by the UDPipe and any language binding.

**Comment by roddar92** [comment]
Great thanks and good luck!
