### ISSUE TITLE
Two nsubj in Ukrainian

### ISSUE THREAD

**Issue by anatoleg** [ufal/udpipe#105]
When parsing "хлопчик купив яблуко" ([the] boy bought [an] apple), udpipe makes both "хлопчик" (boy) and "яблуко" (apple) nsubj of "купив" (bought). This seems fairly pervasive when the direct object's accusative case has the same form as the nominative case.

**Comment by foxik** [comment]
Well, errors like this happen, even if they seems trivial. We are working on UDPipe 2 which has substantially improved performance. so the situation should improve... Closing, but feel free to reopen if needed.
