### ISSUE TITLE
The UDPipe model is loaded into memory successfully, but during inference throws Segmentation Fault

### ISSUE THREAD

**Issue by roddar92** [ufal/udpipe#107]
Dear colleagues,
I have a problem with inference part of UDPipe. Here is some error description:

```
Problem: the UDPipe model is loaded into memory successfully, but during inference throws Segmentation Fault:

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1249051fb0, pid=14766, tid=0x00007f124e2f0700 # # JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09) # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode linux-amd64 compressed oops) # Problematic frame:
# C  0x00007f1249051fb0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again # # If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

Who anybody else had the same problems?

Best regards,
Daria

**Comment by DimaPhil** [comment]
Also faced the same issue when using dataset `english-ud-2.0-170801.udpipe`. Can you please clarify what this issue may be related to? `Model.load` method executes successfully, but then calling `Pipeline::process` throws segmentation fault, similar to the one above.

**Comment by debuggio** [comment]
Hi guys, I'm having exactly the same issue. Did anyone have any progress with this?

**Comment by foxik** [comment]
Sorry for a long delay. I have been on a vacation, so I will look into it sometimes next week. BTW, could you tell me which system and JVM are you all using? The original report seems to be using Linux+Java 1.8 -- is it the case also for @DimaPhin and @debuggio ?

**Comment by DimaPhil** [comment]
@foxik I'm using Ubuntu 18.04 + Java 8, so should be the same

**Comment by DimaPhil** [comment]
@foxik Are there any updates on this issue?

**Comment by karatach1998** [comment]
Make sure the Model instance remains in memory and not deleted by GC. Probably you should pass the reference to the Model object to the outer scope or find some way to make the instance's life much longer than needed.
```
def preprocessor():
    # Model loading preparation...

    udmodel = Model.load(udpipe_filename)
    process_pipeline = Pipeline(udmodel, 'tokenize', Pipeline.DEFAULT, Pipeline.DEFAULT, 'conllu')

    def process_text(text):
        return ' '.join(process(process_pipeline, text=text))
    process_text.udmodel = udmodel  # Fix segmentation fault issue
    return process_text

process_text = preprocessor()
```

**Comment by DimaPhil** [comment]
@karatach1998 That seems to work and helped, thanks a lot!

**Comment by foxik** [comment]
I just tried the official UDPipe 1.2.0 release with OpenJDK 1.8, Oracle Java 8, 10, 11, and everything seems fine. I am closing the issue, but if someone is able to replicate, post the sources and I will investigate more.
