### ISSUE TITLE
predict.LDA newdata

### ISSUE THREAD

**Issue by SebastianKnigge** [ufal/udpipe#108]
I try to use the **predict.LDA_Gibbs** function from the udpipe package for classifying/predicting a new document. Whereas the example in the description seems just to evaluate the training data, I want to use new data.
```{r}
## Get scores alongside the topic model
dtm <- document_term_matrix(x, vocabulary = mymodel@terms)

## Fit a topicmodel using Gibbs
library(topicmodels)
mymodel <- LDA(x = dtm, k = 4, method = "Gibbs")
terminology <- predict(mymodel, type = "terms", min_posterior = 0.05, min_terms = 3)
scores <- predict(mymodel, type = "topics", newdata = dtm)
```
**Does such a usage of the prediction function for a LDA model fit actually make sense?**
to set up the document_term_matrix I used the same vocabulary for the training as well as for the testing (newdata) data.

When evaluating my code (_This is just an example, for more details of my code I can send a link_):
```{r}
predict(chapters_lda, newdata=chapters_dtm_predict, type="topic")
```

The following error message is returned:

> Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

Is there some more information about this function than just the manual? I am specifically interested in the calculation of the posterior.

**Comment by jwijffels** [comment]
This question is related to the R wrapper, please ask the question at https://github.com/bnosac/udpipe
