### ISSUE TITLE
MSVC 2019 compiler error

### ISSUE THREAD

**Issue by thocevar** [ufal/udpipe#109]
The latest Microsoft Visual Studio 2019 compiler gives a compile error (`make PLATFORM=win-vs BITS=32`).

> udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(102): error C2672: 'ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix': no matching overloaded function found

I'm using the compiler shipped with the Visual Studio 2019 Community edition (version 16.2.0). `cl.exe` says `Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86`

**Comment by foxik** [comment]
It can be the case that MSVC 2019 does not compile UDPipe (I do not usually use MSVC, and use 2015 to build UDPipe Win builds). However, I am currently at a conference -- I will look into it sometimes next week.

**Comment by foxik** [comment]
I am not really sure why is MSVC complaining -- it seems to me that the code is valid (even if I am probably wrong given the error :-) and I cannot get any Linux compiler to fail (but I have only moderately old ones). Unfortunately, I currently do not have access to a Windows machine where I could try the MSVC 2019 compiler. Are there any additional information regarding to the error?

**Comment by thocevar** [comment]
I can compile it successfully with tdm-gcc on windows. I'm posting some more error log below. The errors are more or less related to the `gru_tokenizer_network::matrix`.

> .build/cl_deps .build/morphodita-tokenizer-gru_tokenizer_trainer.win-vs-normal32.obj cl /Fo.build/morphodita-tokenizer-gru_tokenizer_trainer.win-vs-normal32.obj /nologo /W 2 /wd4503 /D WIN32 /D UNICODE /D _UNICODE /D _USING_V110_SDK71_ /EHsc /analyze- /O2 /MT /I . /c morphodita/tokenizer/gru_tokenizer_trainer.cpp
gru_tokenizer_trainer.cpp
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(102): error C2672: 'ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix': no matching overloaded function found
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(84): note: while compiling class template member function 'bool ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::train(unsigned int,unsigned int,bool,unsigned int,unsigned int,float,float,float,float,bool,const std::vector<ufal::udpipe::morphodita::tokenized_sentence,std::allocator<_Ty>> &,const std::vector<_Ty,std::allocator<_Ty>> &,ufal::udpipe::utils::binary_encoder &,std::string &)'
        with
        [
            _Ty=ufal::udpipe::morphodita::tokenized_sentence
        ]
morphodita/tokenizer/gru_tokenizer_trainer.cpp(41): note: see reference to function template instantiation 'bool ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::train(unsigned int,unsigned int,bool,unsigned int,unsigned int,float,float,float,float,bool,const std::vector<ufal::udpipe::morphodita::tokenized_sentence,std::allocator<_Ty>> &,const std::vector<_Ty,std::allocator<_Ty>> &,ufal::udpipe::utils::binary_encoder &,std::string &)' being compiled
        with
        [
            _Ty=ufal::udpipe::morphodita::tokenized_sentence
        ]
morphodita/tokenizer/gru_tokenizer_trainer.cpp(40): note: see reference to class template instantiation 'ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>' being compiled
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(102): error C2783: 'void ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix(gru_tokenizer_network_trainer<16>::gru_tokenizer_network_implementation<16>::gru_tokenizer_network::matrix<R,C> &,std::mt19937 &,float,float)': could not deduce template argument for 'R'
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(69): note: see declaration of 'ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix'
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(102): error C2783: 'void ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix(gru_tokenizer_network_trainer<16>::gru_tokenizer_network_implementation<16>::gru_tokenizer_network::matrix<R,C> &,std::mt19937 &,float,float)': could not deduce template argument for 'C'
C:\Temp\udpipe\src\morphodita\tokenizer\gru_tokenizer_network_trainer.h(69): note: see declaration of 'ufal::udpipe::morphodita::gru_tokenizer_network_trainer<16>::random_matrix'
...

**Comment by foxik** [comment]
Keeping open until the fix is confirmed.

**Comment by dlukes** [comment]
I happen to have access to a Windows box, so I thought I might as well test it :)

Checking out the commit just before 703c209, I can confirm that I get errors running `make PLATFORM=win-vs BITS=32` related to `gru_tokenizer_network::matrix`, though not the exact same error codes. I guess this is because the codebase has changed slightly since the compilation error was reported?

More importantly though, 703c209 does indeed fix the problem and compilation succeeds! 🎉 So this issue can be closed IMHO :)

**Comment by foxik** [comment]
Thanks!
