### ISSUE TITLE
Word does not contain offsets

### ISSUE THREAD

**Issue by reckart** [ufal/udpipe#11]
I have trouble anchoring the words produced by the tokenizer on the original text because the Word does not seem to contain character offset information. Could this be added?

**Comment by foxik** [comment]
This is definitely planned. We were discussing how to add this information directly to the CoNLL-U file (in UniversalDependencies/docs#332), but we did not really achieved consensus, which slowed me down.

However, we will have new UDPipe models and UDPipe release after UD 1.4 (UD 1.4 release is planned for Nov 15), and that will contain the required information (maybe not the offsets, but the explicit representation of the spaces between tokens, but that is equivalent).

**Comment by reckart** [comment]
Having the offsets *really* facilitate working with the API. Reconstructing them if space information is present is probably possible, but tedious.

**Comment by foxik** [comment]
Taking that into account. I will see how it will come out.

**Comment by foxik** [comment]
Implemented in UDPipe 1.1. But note that `TokenRange` features are not generated by default, only if `ranges` tokenizer option (or TOKENIZER_RANGES in the API) is used.

**Comment by reckart** [comment]
Works like a charm :)

**Comment by wasiahmad** [comment]
TokenRange seems not always working. I have tried it for the Arabic language and surprisingly, for every word it is not produced. For most work, it is produced, but in a few cases, it doesn't. Wondering why that happens? And what is the solution?
