### ISSUE TITLE
how to force new sentence

### ISSUE THREAD

**Issue by maxtrem** [ufal/udpipe#110]
Hi,
we have a lot of data, that consists of documents with first a title followed by the respective document:

> Resumption of the session
> I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period. 

However when doing the tokenization these titles will often be merged into the following sentence like this:

```
1       Resumption      Resumption      ADP     IN      _       _       _       _       _
2       of      of      ADP     IN      _       _       _       _       _
3       the     the     DET     DT      Definite=Def|PronType=Art       _       _       _       _
4       session session NOUN    NN      Number=Sing     _       _       _       SpacesAfter=\n
5       I       I       PRON    PRP     Case=Nom|Number=Sing|Person=1|PronType=Prs      _       _       _       _
6       declare declare VERB    VBP     Mood=Ind|Tense=Pres|VerbForm=Fin        _       _       _       _
7       resumed resume  VERB    VBD     Mood=Ind|Tense=Past|VerbForm=Fin        _       _       _       _
8       the     the     DET     DT      Definite=Def|PronType=Art       _       _       _       _
```

Is there to prevent this? For example by somehow forcing UDPipe to start a new sentence after seeing a `'\n'`?

Thanks in advance!

**Comment by foxik** [comment]
If you have sentence boundaries, you can use `--tokenizer=presegmented` and then every `\n` separates a sentence.

Otherwise, if you have only paragraph boundaries (i.e., the title is a separate paragraph), use an empty line (i.e., two consecutive `\n`) to separate two paragraphs (i.e., to force end of sentence). So
```
Resumption of the session

I declare...
```

Closing, but feel free to reopen if needed.

**Comment by maxtrem** [comment]
Thank you for your reply! There're no sentence boundaries. Actually I was already using your proposed solution :) 
However this has the drawback that there is a `# newpar` after every line. 
Is there a way then to only set the `# newpar` for four consecutive `\n` instead of two?

**Comment by maxtrem** [comment]
Hi again,
as previously said I we were using the method with two consecutive `\n` however this does not work for all the cases. Here is an example where a single token is added into the next sentences even though separated by two consecutive `\n`.

> Transparentnost.com
> MOSKVA – Nedávno jsem se po prodlouženém víkendu v Moskvě vrátila do Hvězdného městečka (ruského kosmického výcvikového střediska) a zarazilo mě, jak mnoho – a jak málo – se tu toho změnilo za 20 let od jara 1989, kdy jsem sem přijela poprvé.

Resp.:

> Transparentnost.com
> 
> MOSKVA – Nedávno jsem se po prodlouženém víkendu v Moskvě vrátila do Hvězdného městečka (ruského kosmického výcvikového střediska) a zarazilo mě, jak mnoho – a jak málo – se tu toho změnilo za 20 let od jara 1989, kdy jsem sem přijela poprvé.

Results in:

```
# newpar
# sent_id = 36
# text = Transparentnost.com MOSKVA – Nedávno jsem se po prodlouženém víkendu v Moskvě vrátila do Hvězdného městečka (ruského kosmického výcvikového střediska) a zarazilo mě, jak mnoho – a jak málo – se tu toho změnilo za 20 let od jara 1989, kdy jsem sem přijela poprvé.
1       Transparentnost.com     Transparentnost.com     PROPN   ADJD    _       _       _       _       SpacesAfter=\n\n
2       MOSKVA  MOSKVA  PROPN   NE      Case=Nom|Gender=Masc|Number=Sing        _       _       _       _
3       –       –       PUNCT   $.      _       _       _       _       _
4       Nedávno Nedávno PROPN   NE      Case=Nom|Gender=Masc|Number=Sing        _       _       _       _
5       jsem    js      PRON    PDS     Case=Dat|Gender=Masc|Number=Sing|PronType=Dem   _       _       _       _
.
.
```

Any ideas how to get around this?

Thanks!

**Comment by foxik** [comment]
Hi, the problem with the URL/email at the end of lines has been resolved. There is still now no way to force paragraphs on four newlines or similar, but future development will move from UDPipe to LinPipe, so I am closing this.
