### ISSUE TITLE
Rake not capturing most frequent keywords

### ISSUE THREAD

**Issue by rboga** [ufal/udpipe#115]
Hi
I have a million questions asked by consumers which I am analyzing. Close to 25% of them are to do with phrase "item number". But when i run Rake through it, I don't get that phrase at all in the list. Here is the code I am using. I can't figure what is going wrong. can you help.

anotated_df <- data.frame(udpipe_annotate(udmodel_english, data$question))

Using RAKE
stats <- keywords_rake(x = anotated_df, term = "lemma", group = "doc_id",
relevant = anotated_df$upos %in% c("NOUN", "ADJ"))
head(subset(stats, freq > 3), 26)

**Comment by foxik** [comment]
As this concerns the R wrapper, adding @jwijffels.

**Comment by jwijffels** [comment]
This question is related to the R wrapper which builds some extra functionalities on top of the udpipe annotation. R issues should be reported at https://github.com/bnosac/udpipe/issues/66
@foxik Please close the issue, same question was asked here https://github.com/bnosac/udpipe/issues/66

**Comment by foxik** [comment]
Thanks!
