### ISSUE TITLE
Multiprocess training

### ISSUE THREAD

**Issue by svetlana21** [ufal/udpipe#119]
Hello!
I didn't find information about training using several workers. Is it supported?

**Comment by foxik** [comment]
Not yet -- it is planned for 2.0.

**Comment by snvv** [comment]
Hello
**txt_sentiment** function doesn't support multithreading yet. 
Using a large corpus, this could be a "problem".
It would be a nice addition if you support it in a future version.
Thank you
Sotiris

**Comment by foxik** [comment]
Right. Multithreaded (and even GPU) support is definitely planned, but not yet finished...

**Comment by jwijffels** [comment]
@snvv txt_sentiment is part of the R package, please report issues/remarks on the right repository https://github.com/bnosac/udpipe.
@svetlana21 The question on speeding up training is also asked at https://github.com/ufal/udpipe/issues/26. Please redirect questions / remarks on GPU / Multiprocess training to that issue https://github.com/ufal/udpipe/issues/26.
