### ISSUE TITLE
Automatic loading of udpipe model when running on command line

### ISSUE THREAD

**Issue by Cdk29** [ufal/udpipe#120]
Good morning,
When I try to run a R script  from the command line that import the library udpipe I got the following :

```
Loading required package: NLP
Downloading udpipe model from https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.4/master/inst/udpipe-ud-2.4-190531/english-ewt-ud-2.4-190531.udpipe to /home/NET1/rollaet/english-ewt-ud-2.4-190531.udpipe
Visit https://github.com/jwijffels/udpipe.models.ud.2.4 for model license details
2019-12-18 10:53:01 URL:https://raw.githubusercontent.com/jwijffels/udpipe.models.ud.2.4/master/inst/udpipe-ud-2.4-190531/english-ewt-ud-2.4-190531.udpipe [16477964/16477964] -> "/home/NET1/rollaet/english-ewt-ud-2.4-190531.udpipe" [1]
```
I am a bit puzzled by this behavior, especially since I already have locally download the udpipe models. Is there a way to disable this automatic download ? Everything is fine when using Rstudio,

**Comment by martinpopel** [comment]
This question is related to the R wrapper which builds some extra functionalities on top of the udpipe annotation. R issues should be reported at https://github.com/bnosac/udpipe/issues
cc: @jwijffels

**Comment by jwijffels** [comment]
Yes, please report at https://github.com/bnosac/udpipe/issues

**Comment by jwijffels** [comment]
Please close this issue. It is expected behaviour if the user did not change the overwrite = TRUE argument when running udpipe or udpipe_download_model. 
Note issues related to the R package should be asked at https://github.com/bnosac/udpipe/issues

**Comment by foxik** [comment]
Definitely. BTW, I just send you and invitation link with triage access to UDPipe, so that you can manage issues (and pull requests) -- feel free to decline, but you have been quite active here, so I feel it makes sense.

**Comment by jwijffels** [comment]
No problem. I'll do some triage - especially related to the R wrapper and if there are basic questions.

**Comment by foxik** [comment]
Thanks!
