### ISSUE TITLE
AArch64 architecture support

### ISSUE THREAD

**Issue by Shyamniper** [ufal/udpipe#121]
Installation fails on on Raspberry pi 4

**Comment by jwijffels** [comment]
FYI. Issue reported also here https://github.com/bnosac/udpipe/issues/71
User fixed it by adding -latomic compiler flag

**Comment by foxik** [comment]
Thanks. The `libatomic` library is required when atomic operations cannot be implemented using native instructions, in which case `__atomic_*` functions are used, and these are not linked in by default. However, different compiler runtimes provides these functions in a different way (especially clang allows either using libgcc_s and libatomic, or compiler-rt), so adding `libatomic` unconditionally is not a good idea.

However, the AArch64 is currently out-of-scope for us, given that we are (yes, with a huge delay) planning to use TensorFlow as backend, and TensorFlow does not seem to support aarch64. So I am marking as wontfix.
