### ISSUE TITLE
Parse API

### ISSUE THREAD

**Issue by arademaker** [ufal/udpipe#122]
Is it possible to have any number related to the level of confidence of the parser for a given sentence? Is it possible to get more than one parse tree for a given sentence?

**Comment by foxik** [comment]
The internal library which UDPipe uses for parsing (Parsito) provides a log likelihood of a tree, and by default performs beam search of size 5, so it generates 5 most probable trees.

However UDPipe does not utilize any such information and just throws it away. Currently I do not plan to provide access to such information in public API (I am concentrating on changing the architecture to a much better one), but if you are interested, you can look in
https://github.com/ufal/udpipe/blob/31f0b8c77a7a68017e60726ed385227db673315b/src/parsito/parser/parser_nn.cpp#L188-L195
Here the final cost is computed (it is stored as an average cost per decision) and the best tree is chosen.

Closing for the time being; we may revisit the decision after the architecture is improved.
