### ISSUE TITLE
Does UDPipe provide NER tags?

### ISSUE THREAD

**Issue by wasiahmad** [ufal/udpipe#124]
I am using UDPipe in python. I can get the POS tags and DepRel info, I am wondering is it possible to get the NER tags too?

**Comment by martinpopel** [comment]
Not (yet). See http://ufal.mff.cuni.cz/nametag (pre-trained models are available for English and Czech only, but you can train your own models).

**Comment by foxik** [comment]
Exactly, not yet. However, NER is definitely planned (in Q4 2020 or so), and even NEL is planned :-) Closing.
