### ISSUE TITLE
Dealing with non-projectivity.

### ISSUE THREAD

**Issue by lucasrct** [ufal/udpipe#128]
I am dealing with several sentences that have non projective parse trees and it seems that UDpipe can't properly handle them. For instance, the sentence

> «Amadeu Cury» nasceu em Guaxupé (MG) no dia 13 de maio de 1917, filho de Espir Cury e de Nazaré Cury. 

(«Amadeu Cury» was born in Guaxupé (MG) on 13 May 1917, son of Espir Cury and Nazaré Cury)

In my analysis, **son** should be `appos` of **Amadeu**, but UDpipe assigns son as `appos` of born (the root). This analysis procude a non-projective arc.
The model was initially trained on UD-Bosque data. To try to enhance the model, I manually selected and revised 250 similar sentences (with roughly the same structure, i.e., _"someone was born in somewhere on some date, son of ..."_) and added 150 of them to the Bosque data to re-train the model. 
However, the model still assigns **"son"** as `appos` of the **root verb**. Even testing on the sentences that were in the training data, it still produces the same error. 
There were other errors the model made when parsing the sentence in which after adding the re-trained sentences, it started to get right. My point is, **_can UDpipe really deal with non-projective trees at the point where it can generate them? Or it is really a "data" problem?_** 
To me, assign **son** as `appos` of a verb, in this case makes no sense. 
Looking at the paper where [parsito was based on](http://ufal.mff.cuni.cz/parsito#publications), it says that it can indeed handle such cases, but, to me, it seems that the parser always avoids creating such non-projective parse trees.

**Comment by martinpopel** [comment]
I agree non-verb `appos` of a verb is usually an error or an [ellipsis](https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis). Most of [these cases in English EWT](http://hdl.handle.net/11346/PMLTQ-GYMN) are actually annotation errors, but some are ellipses.
I think your sentence can be also interpreted as an ellipsis ("he was born in Guaxupé, *and he was born as* son of Cury"), but in that case the deprel should not be `appos`.

UDPipe's parser offers three [transition systems](http://ufal.mff.cuni.cz/udpipe/users-manual#model_training_parser): `projective`, `swap` and `link2`. The [UD2.5 UDPipe pre-trained model](https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-3131) for `pt_bosque` was trained with `transition_system=link2;transition_oracle=static` (as you can see in the `params_parser` file in `udpipe-ud-2.5-191206-reproducible_training.zip`). This is a partially non-projective system. You may get better results on non-projective trees with `transition_system=swap`. If you re-train the model yourself, note that the default is `transition_system=projective`, **which produces only projective trees**.

**Comment by arademaker** [comment]
Hi @martinpopel, yes, definitely we may have many possible interpretations. I like your analysis although  `born as son ...`  is not very common construction in Portuguese. Anyway, if we take your idea the paraphrase of the sentence would be:

> «Amadeu Cury» nasceu em Guaxupé (MG) no dia 13 de maio de 1917,  _ele nasceu_ filho de Espir Cury e de Nazaré Cury.

In that case, `filho` would be linked to `nasceu` by `conj` making a coordination of the two clauses. But the second one would have the non-core argument `filho de ...` promoted to the head of the clause. The coordination would be less informative than the `appos` which means that any further mining of this tree for information extraction would be much more complicated. Does it make sense?

Thank you very much for the direction on how to train UDPipe using a different transition system.  I am supervising @lucasrct on this thesis, so I hope that with this feedback we can make progress.

**Comment by lucasrct** [comment]
@martinpopel, thank you for your answer!

**Comment by vcvpaiva** [comment]
For what's worth it, for an analysis of the sentence as ellipsis we  would have instead:
(«Amadeu Cury» was born in Guaxupé (MG) on 13 May 1917. Amadeu Cury was the  son of Espir Cury and Nazaré Cury.)

**Comment by arademaker** [comment]
I believe we can close it.
