### ISSUE TITLE
Method to query tagger and parser tagsets from model

### ISSUE THREAD

**Issue by reckart** [ufal/udpipe#13]
It would be great if the library API would export methods to query the tagsets used by the tagger and parser. Could you please also include them in the Java API?

**Comment by foxik** [comment]
For language-specific POS tags and morphological features, we do not have a fixed set (well, the current implementation does, but we have models in mind which will generate these component-wise),
so I am reluctant to add these tagset query methods (the implementation could return a cartesian product of the factors, but that would result in many "false" results).

**Comment by reckart** [comment]
Maybe it would be possible to query for the possible components? For some tagsets, e.g. PTB or STTS, I suppose there would only be a single component while for MULTEX-like rich tagsets there would be multiple?

**Comment by foxik** [comment]
I agree that it could be useful and that for some models there would be a fixed set; however, I am not planning to work on it in the near future.

Leaving the issue open in order to remind me.

**Comment by reckart** [comment]
Is the format of the binary model files documented somewhere? Maybe I could extract the info directly from the files.

**Comment by foxik** [comment]
Closing, as future development will move from UDPipe to LinPipe; there, this feature will be provided.
