### ISSUE TITLE
Adding TokenRanges for data that has already been tokenized

### ISSUE THREAD

**Issue by danielhers** [ufal/udpipe#131]
The `--tokenizer=ranges` option adds `TokenRange=` to the `MISC` field, according to the character ranges in the text.
Can I use UDPipe on an existing (gold/parsed) CoNLL-U file to do nothing but add these ranges according to the existing tokenization?

**Comment by foxik** [comment]
No, unfortunately not, you need to do it manually. But you could use Python UDPipe API (which is however not much documented, only the C++ binding wrapped by Swig is at http://ufal.mff.cuni.cz/udpipe/api-reference#cpp_bindings_api) to load the file and then set the ranges using `.setTokenRange`.
