### ISSUE TITLE
new language - Macedonian

### ISSUE THREAD

**Issue by fukidzon** [ufal/udpipe#132]
In our project we use spacy-udpipe for languages which are not covered by original spaCy models, but there is a request for **Macedonian language** which is not covered in udpipe models.

I found already some info how to make a UD Treebank for new language (https://universaldependencies.org/how_to_start.html) which can be used for training of the models. 

Just a practical question before I actually start to work on it: 
Approximately **how much data (text) and how much time is needed** to prepare the UD Treebank and for training a reasonably good udpipe model (with dep, pos tagger and lemmatizer)?

**Comment by martinpopel** [comment]
@fukidzon: You should get in contact with Vladimir Cvetkoski, the author of https://github.com/UniversalDependencies/UD_Macedonian-MTB and coordinate your efforts. See also https://universaldependencies.org/release_checklist.html.

> how much data (text) and how much time is needed 

Unsurprisingly, the more training data the better for the final parser quality, but the domain match (of the training data and your expected test data) is also important. 
Annotating UD takes a lot of time, probably more than you would expect, especially if you don't have any prior experience (thus it may be a good idea to ask at the UD mailing list or [issues](https://github.com/UniversalDependencies/docs/issues) and find someone to cooperate with).
I would suggest to use cross-lingual / multi-lingual parsing techniques to bootstrap the Macedonian treebank, taking advantage of the available UD treebanks for Bulgarian, Croatian, Serbian and Slovenian. Then manually fix the automatic annotation, ideally hiring linguists who understand Macedonian and UD. Even a small Macedonian treebank may help to improve the multi-lingual parser, which can be used for another round of bootstrapping/pre-annotation.

**Comment by fukidzon** [comment]
@martinpopel Thank you for such fast response! I'll start by contacting Vladimir Cvetkoski ...

**Comment by foxik** [comment]
Thanks for your interest!

Closing the issue; if you are interested in creating a UD treebank, https://github.com/UniversalDependencies/docs/issues is probably a more appropriate place.
