### ISSUE TITLE
UnicodeDecodeError while training

### ISSUE THREAD

**Issue by rasimuvaikas** [ufal/udpipe#134]
Hi, I am trying to train a new model using the ufal.udpipe package on Python. The Trainer.train() command works so far as to selecting the best options for the tagger, the tokenizer and the parser, but right before it can return a model it throws a UnicodeDecodeError ("UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 25: invalid start byte").

    static string train(const string& method, const Sentences& train, const Sentences& heldout,
                        const string& tokenizer, const string& tagger, const string& parser,
                        ProcessingError* error = nullptr);

As arguments for the train and heldout parameters required above I am using lists of Sentence objects, which were originally a long Python string in conllu format. The string is read from a conllu file with 'utf8' encoding. 

I have tried playing around with encodings, but nothing seems to work. Moreover, I am confused as to what the .train() method is supposed to return. In the original C++ version it returns a boolean, and "if the training succeeded, true is returned and the model is saved to the given os stream" (http://ufal.mff.cuni.cz/udpipe/api-reference#trainer_train), but in Python it's supposed to return a string and I am not sure how I am supposed to store the model itself? 

Perhaps if someone could elaborate on what exactly this method does and returns, I could find a way to solve my issue.

Thank you

**Comment by jowagner** [comment]
A first step would be to confirm that Python3 agrees with you that the `.conllu` file is valid `utf8`: `open('myfile.conllu', 'rb').read().decode('utf-8')` should produce no error message. If this is ok but udpipe encounters the above error at a non-zero position (you quoted position 25), this will mean that you or udpipe has sliced and recombined binary data. (At position zero, slicing alone can produce the error.) To debug this, you could verify each string before passing it to udpipe that it is valid `utf-8`. If your strings are all fine the error needs to be hunted inside udpipe. If you can provide a minimal example that triggers the error that would help the developers immensely.

**Comment by foxik** [comment]
Oh, I think the problem is in the bindings -- Python assumes the output is utf-8 string, but it is really just a sequence of binary bytes. There will need to be defined a new type (something like Bytes) which SWIG will not convert to utf-8; but returning `bytes[]` is not as easy as I hoped in SWIG... But I will fix it eventually.

**Comment by huberemanuel** [comment]
Any updates on this?

**Comment by huberemanuel** [comment]
I was able to run the training process updating the `pystrings.swg`, just copying the updated file from [here](https://github.com/swig/swig/blob/master/Lib/python/pystrings.swg).

The output string needs to be encoded to utf-8 with surrogateescape, more info [here](http://www.swig.org/Doc3.0/Python.html#Python_nn77).

Sample snippet to train with Python (after above changes):

```python
from ufal.udpipe import Trainer
trainer = Trainer()
model = trainer.train("morphodita_parsito", train_sentences, heldout_sentences, Trainer.DEFAULT, Trainer.DEFAULT, Trainer.DEFAULT)
model_file = open("mymodel.model", "wb")
model_file.write(m.encode("utf-8", errors="surrogateescape"))
model_file.close()
```

Btw, I shall make a PR with these changes, that will enable full support to Python.

**Comment by jowagner** [comment]
I assume this arises from a predicted lemmatisation edit script producing a lemma that is invalid UTF-8. While surrogate escapes allows the predicted lemma to be passed to Python, the escapes will increase string distance to valid lemmas e.g. in a fuzzy dictionary lookup or confuse a character LSTM in a pipeline model processing the lemmas. No problem if this happens rarely but if it happens often enough it might be a good idea to add a penality for ill-formed UTF-8 to the loss function in training.
