### ISSUE TITLE
Transform .CSV to Token and POS tagging

### ISSUE THREAD

**Issue by sarahmnalifa** [ufal/udpipe#135]
Hello, im a newbie and im trying to get to work with Rstudio for my final project. Does udpipe can tokenize and tagger with .csv data? i want to do Tokenization and Parts of Speech Tagging with my .CSV data using udpipe package but i still dont know how to import the .csv data and save the result. any solution about this?

my data: https://drive.google.com/file/d/1EI5r83xLOZUKCqQfWvMFV31EGj11GIOP/view?usp=sharing

**Comment by jwijffels** [comment]
Please ask questions about the R package at https://github.com/bnosac/udpipe
And programming questions at stackoverflow. That's that site for such questions. Either way have you tried something like the following?

```
library(udpipe)
library(readtext)
x <- readtext("C:/Users/Jan/Desktop/06_stopword.csv")
anno <- udpipe(x, "indonesian")

```

**Comment by sarahmnalifa** [comment]
i've tried the following code but it still didnt work

**Comment by jwijffels** [comment]
@sarahmnalifa 
Thanks for your interest in udpipe
- In general github issues are for either reporting of bugs / improvements / unexpected behaviour.
- Questions about programming can be asked on stackoverflow where you can get answers on reproducible examples

**Comment by sarahmnalifa** [comment]
i already found the solution, thank you for the respond!
