### ISSUE TITLE
Help on Parsing a pre-tokenized sentence in Python

### ISSUE THREAD

**Issue by wasiahmad** [ufal/udpipe#137]
I am using the Model class (https://github.com/ufal/udpipe/blob/master/bindings/python/examples/udpipe_model.py) to parse sentences (in multiple languages) in Python. However, I have a sentence that is tokenized and I don't know how to parse it using the Python Model class.

```python
sentences = model.tokenize(text, 'ranges;presegmented')
for s in sentences:
    model.tag(s)
    model.parse(s)
conllu = model.write(sentences, "conllu")
print(conllu)
```

**Comment by foxik** [comment]
You need to construct an appropriate `ufal.udpipe.Sentence`, which you can then pass to `model.tag` and `model.parse`.
You can:
- construct the ufal.udpipe.Sentence manually (it has an `.addWord` method);
- call `model.read` with `input_format=vertical` and pass the input sentence in `vertical` [input format](https://ufal.mff.cuni.cz/udpipe/1/users-manual#run_udpipe_input)

**Comment by maayanorner** [comment]
Hi,

I am trying to hack a solution with another tokenizer, however, the proposed method does not handle multi-word tokens. Is there any way to use addWord with some delimiter, or any method that supports multi-word tokens? I could not find a way to do it properly in the source code (which might be my fault).

For example:
```
def _convert_to_udpipe_sentences(tokenized_sentences):
    sentences = []
    for tokens in tokenized_sentences:
        if len(tokens) == 0:
            continue
        sentence = Sentence()
        for token in tokens:
            word = ' '.join(token) # what can I do here?
            sentence.addWord(word)
        sentences.append(sentence)
    return sentences
```


Thanks!
