### ISSUE TITLE
Hyperparameter settings from pre-trained models

### ISSUE THREAD

**Issue by liljao** [ufal/udpipe#14]
Great tool, thanks for making it available.

Is there some way of obtaining the hyperparameter settings that were used for the individual pre-trained models available from Lindat?

**Comment by foxik** [comment]
Thank you for your interest :-)

The hyperparameters for the UD 1.2 models are stored directly in the repository, see https://github.com/ufal/udpipe/tree/master/training/models-ud-1.2. The hyperparameters are stored in the three `params_*` files. You can train individual language models using the `train.sh` script.

Note that for training you need several files:
- UD 1.2
- word embeddings computed on UD 1.2 files -- these can be generated using https://github.com/ufal/udpipe/blob/master/training/ud-1.2-embeddings/gen.sh script
- raw text data to train the tokenizer -- these are generated by https://github.com/ufal/udpipe/blob/master/training/ud-1.2-raw-texts/raw_texts.sh script; the script copies W2C data directly from internal network path, but you can get the exact same data from Lindat at http://hdl.handle.net/11858/00-097C-0000-0022-6133-9

Happy hacking :-)
