### ISSUE TITLE
non-ascii paths

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#151]
I had several Windows users of the R package who use models in paths with non-ASCII characters

When e.g. executing `ufal::udpipe::model::load('C:/Users/Jan/Dropbox/Work/RForgeBNOSAC/BNOSAC/udpipe/àb/italian-isdt-ud-2.5-191206.udpipe')` this gives a nullptr when calling loading the model. 
Is there a C++ way to cleanly handle this?

```
model* model::load(const char* fname) {
  ifstream in(fname, ifstream::in | ifstream::binary);
  if (!in.is_open()) return nullptr;
  return load(in);
}
```

**Comment by foxik** [comment]
Hi,

I was not aware that the filenames should not be UTF-8 on Windows ;-) If https://stackoverflow.com/a/30831401/14517809 is correct, it would be best to convert the filenames to UTF-16 on Windows and use the `wchar_t` overload.

Keeping open as a remainder to fix it (I plan maintainance version of UDPipe 1.3 sometime in the future).
