### ISSUE TITLE
Plan about UDPipe 3

### ISSUE THREAD

**Issue by innerNULL** [ufal/udpipe#153]
Hi, is there any plan or timeline about UDPipe 3?
Thanks~

**Comment by foxik** [comment]
Anything specific. I had to stop working on software during pandemic, and while it seemed the global situation is getting better a month ago or so, the pandemic situation might easily reverse it seems.

Anyway, we are still months of work away from a release, so we are talking about Q1,Q2 of 2022 if nothing unexpected arises...
