### ISSUE TITLE
xpos abbreviations for English

### ISSUE THREAD

**Issue by czopluoglu** [ufal/udpipe#155]
Is there a reference we can find what the abbreviations returned under the column `xpos` mean for English?

I can find the ones for `upos` at this link (https://universaldependencies.org/u/pos/index.html); however, the ones under `xpos` require a lot of guesswork.

**Comment by martinpopel** [comment]
From the UDPipe point of view, XPOS is just another tag to predict and the predicted values are based on whatever was used for XPOS in the training data.

In CoNLL-U, [XPOS is a treebank-specific PoS tag](https://universaldependencies.org/format.html), so there is no unified reference. It is not needed in [UD](https://universaldependencies.org) (there are treebanks without XPOS). Usually, it contains legacy pre-UD pos tags. For example, English uses [PennTB PoS tags](https://ufal.mff.cuni.cz/pcedt3.0/pubs/english-treebank-postags.pdf), Czech uses [PDT tags](https://ufal.mff.cuni.cz/pcedt3.0/pubs/TR_PDT_C_morph_manual.pdf) - in both cases these XPOS tags encode not only the part of speech, but also other morphological features, which are encoded also in the CoNLL-U FEATS column. For other languages/treebanks, search their documentation (at least, the [metadata](https://github.com/UniversalDependencies/UD_English-EWT#metadata) should contain info such as `manual native`).
