### ISSUE TITLE
train a model in stages

### ISSUE THREAD

**Issue by hezaoke** [ufal/udpipe#159]
Hi,

I wonder if there is a way to train the language model in several stages with udpipe_train() or some other functions that I am not aware of. Right now, I have to train the model anew every time if I add more training data. If there is a way to continue to train an existing model with more data, that would save a lot of time.

Thanks,
Alan

**Comment by foxik** [comment]
Hi,

no, unfortunately not, you have to retrain it all again. Currently it is not possible, some parts of the training information is thrown away before saving the trained mode (which would need to be kept to able to continue with the training).
