### ISSUE TITLE
training for ud 2.10

### ISSUE THREAD

**Issue by hezaoke** [ufal/udpipe#160]
Hi! I trained my own language model with training data from ud 2.10. However, the performance of this language model seems to be not as good as the pre-compiled language models described here: https://ufal.mff.cuni.cz/udpipe/2/models.

I wonder if it is possible to get the hyperparameters for the training of the pre-complied 2.10 models, or if we could access the 2.10 pre-complied 2.10 models in R or python.

Thanks!

**Comment by foxik** [comment]
The UD 2.10 models are trained using UDPipe 2, and can only run in UDPipe 2 -- that is just a Python prototype (not available in R or `ufal.udpipe` package) -- you can download UDPipe 2 here https://github.com/ufal/udpipe/tree/udpipe-2 and the hyperparameters used for training are the ones in https://github.com/ufal/udpipe/blob/udpipe-2/udpipe2.py and in https://github.com/ufal/udpipe/blob/udpipe-2/scripts/train.sh. A GPU is needed for training and recommended during inference (the inference speed on CPU would be dozens of words per second, on a GPU it is something like two thousand w/s).

If you are using UDPipe 1, its performance is substantially worse.

We are also working on UDPipe 3, which will be again a C++ application and available from various languages (Python bindings, R, console app, ...). But it is still months from being released.
