### ISSUE TITLE
Incorrect upos and dependencies on copulas ?

### ISSUE THREAD

**Issue by gloignon** [ufal/udpipe#164]
Hello, 

Using French models such as French-GSD and ParTUT, a sentence such as _Le chat est petit_ will result in a different structure than it's presumably equivalent _Le chat semble petit_.  This happens whenever there is an être verb with the cop dep_rel tag. 

For comparison, here's the être version:
![image](https://user-images.githubusercontent.com/12416756/213798743-508dac08-2239-4062-84ed-4e7f7681fcee.png)

The verb is tagged as an AUX when it should be a VERB as _être_ is not used as an auxiliary here. The head is set to _petit_ when it should be _être_.

Now the _sembler_ version, which should be equivalent:
![image](https://user-images.githubusercontent.com/12416756/213798816-f72e0be8-3e22-4648-8877-4d90f95df63c.png)

That one has the right structure and tags.

**Comment by martinpopel** [comment]
This is the correct behavior according to [the Universal Dependencies guidelines](https://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses). Citing [the French-specific guidelines](https://universaldependencies.org/fr/dep/cop.html): _In French, only the verb être appears as a copula._

**Comment by gloignon** [comment]
The copula tag is not a problem in itself. Here the verb is incorrectly
tagged as an AUX and the structure is incorrect.

**Comment by martinpopel** [comment]
When the verb être is used as a copula, it should be tagged as [AUX](https://universaldependencies.org/u/pos/AUX_.html), which means an auxiliary verb in UD. AUX should depend on the main verb.
Please read [the UD annotation guidelines](https://universaldependencies.org/guidelines.html) before reporting bugs of this kind. If there is anything unclear in the UD guidelines, you can report issues [there](https://github.com/universaldependencies/docs/issues). This issue tracker should focus on technical errors of the UDPipe parser. The parser is trained on UD treebanks, so before reporting an issue about wrong parsing, one should check how is a given phenomenon annotated in the respective training treebanks. If it is the same (as in this example with copulas), it is definitely not an error of UDPipe - it just reflects the style of the training data.

**Comment by foxik** [comment]
Thanks, @martinpopel, closing.
