### ISSUE TITLE
Wheels for newer pythons 

### ISSUE THREAD

**Issue by PrimozGodec** [ufal/udpipe#165]
Currently, ufal-udpipe provides only wheels for Python 3.8 and older. Since udpipe is included in [Orange3-text](https://github.com/biolab/orange3-text), users without compilers have issues installing it (especially now when the Orange3 installer is based on python 3.9).

Can you provide wheels for newer versions of Python? I do not know how you build wheels ([I found this script](https://github.com/ufal/udpipe/blob/master/releases/pypi/gen.sh)), but if you are ok, I can create a PR with GH actions workflow that would build wheels for all platforms and python versions. Please let me know what you think.

**Comment by foxik** [comment]
Hi,

I plan to soon release UDPipe 1.3, which will of course include wheels for all current Python versions. But I can upload also such wheels for the current UDPipe 1.2 -- I will try doing it later today.

**Comment by foxik** [comment]
All wheels for 1.2.0.3 are building now.

**Comment by foxik** [comment]
Published wheels for Python 3.6-Python 3.11, and also for ARM macOS.

**Comment by PrimozGodec** [comment]
@foxik, thanks a lot for your quick intervention. :)
