### ISSUE TITLE
Problems  run udpipe2_server.py

### ISSUE THREAD

**Issue by rjzevallos** [ufal/udpipe#167]
Hello I would like run "udpipe2_server.py" but I get this msg:

udpipe2_server.py [-h] [--batch_size BATCH_SIZE] [--logfile LOGFILE] [--max_request_size MAX_REQUEST_SIZE]
                         [--preload_models [PRELOAD_MODELS [PRELOAD_MODELS ...]]] [--threads THREADS] [--wembedding_server WEMBEDDING_SERVER]
                         port default_model models [models ...]
udpipe2_server.py: error: the following arguments are required: port, default_model, models

So, What commands do i need to put to be able to run this model (catalan-ancora-ud-2.10-220711) locally?

**Comment by foxik** [comment]
Hi,

please refer to the readme in the `udpipe2` branch of the repository here: https://github.com/ufal/udpipe/tree/udpipe-2.

Cheers!

**Comment by rjzevallos** [comment]
Can you tell me what would be the syntax to run the English model as an example please?
