### ISSUE TITLE
compound not correctly tagged to its head

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#176]
Text:
MALVERN, Pa., Aug. 09, 2023 (GLOBE NEWSWIRE) -- Galera Therapeutics, Inc. (Nasdaq: GRTX), a clinical-stage biopharmaceutical company focused on developing and commercializing a pipeline of novel, proprietary therapeutics that have the potential to transform radiotherapy in cancer, today announced that it has received a Complete Response Letter (CRL) from the U.S.Food and Drug Administration (FDA) regarding the Company’s New Drug Application (NDA) for avasopasem manganese (avasopasem) for radiotherapy-induced severe oral mucositis (SOM) in patients with head and neck cancer undergoing standard-of-care treatment.

issue part from above text : for avasopasem manganese

compound not correctly tagged to its head.

**Comment by foxik** [comment]
See https://github.com/ufal/udpipe/issues/175#issuecomment-1768291600.

Cheers!
