### ISSUE TITLE
new requirement in parsers

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#177]
Hi Sir,
Shankar from Bangalore, India
------------------------------------------------
Present available parsers are finding grammar relations in the text.
-------------------------------------------------
Can you make the parser, which can find?
1a) solution 
2a) problem 
2b) requirement
-------------------------------------------------
examples:
1) I found money when cleaning.
money   :	solution	
cleaning :	requirement

2) I want to build a bridge.
build     :	solution	
bridge   :	requirement
		
3)Fever is not allowing me to work.
fever     :	problem		
work     :   solution

**Comment by foxik** [comment]
The intent of these issues is to allow UDPipe bug reports, but this one has no direct relation to UDPipe, so I am closing it.

**Comment by Shasetty** [comment]
Hi sir,

I totally respect the decision process of this form.
--------------------------------
My main requirement, is to understand any given text, by using 
1) common sense 
2) grammar
---------------------------------
As UDpipe is good in grammar, 
incorporating common sense in UDPIPE will make it complete.
---------------------------------
lets us consider common sense step by step
-----------
1)To find the real meaning of any text, 
we have to:

a1) read them 
a2) analyze them 
a3) understand them
------------------------------------------
2)What are the real challenges in understanding any text?

Taking entire economy (USA or INDIA) as an input.

b1) We are not experts, in all the fields.
b2) Information keeps flowing from all the fields.
-----------------------
C1) informations will be unique
C2) hidden information
C3) indirect information
C4) providing unwanted information
C5) and many more

------------------------------------------
3)	Style of available text

d1) Big text with many paragraph
d2) small text with few paragraph
d3) 1 paragraph
d4) 1 liners
d5) single words
------------------------------------------
4)	Availability of time
----------------------------------------

5)	How to analyze the text to understand the text?

E1) problems are unique
E2) solutions for the problem will be unique

E3) requirements are unique
E4) solution for the requirement will be unique

E5) Decision process will be universal (common sense)
----------------------------------------
6)	What is the universal decision process?

Decision process, is looking for;
F1) problem
F2) requirement
----------
F3) solution
----------
F4) path that leads for problem
F5) path that leads for requirement
F6) path that leads for solution

considering the above inputs , i would like to see the text ,analyze them and understand them as per point 6, and find the main word using parsers(grammar)
