### ISSUE TITLE
new requirement in parsers

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#178]
Hi sir,

I totally respect the decision process of this form.
--------------------------------
My main requirement, is to understand any given text, by using 
1) common sense 
2) grammar
---------------------------------
As UDpipe is good in grammar, 
incorporating common sense in UDPIPE will make it complete.
---------------------------------
lets us consider common sense step by step
-----------
1)To find the real meaning of any text, 
we have to:

a1) read them 
a2) analyze them 
a3) understand them
------------------------------------------
2)What are the real challenges in understanding any text?

Taking entire economy (USA or INDIA) as an input.

b1) We are not experts, in all the fields.
b2) Information keeps flowing from all the fields.
-----------------------
C1) informations will be unique
C2) hidden information
C3) indirect information
C4) providing unwanted information
C5) and many more

------------------------------------------
3)	Style of available text

d1) Big text with many paragraph
d2) small text with few paragraph
d3) 1 paragraph
d4) 1 liners
d5) single words
------------------------------------------
4)	Availability of time
----------------------------------------

5)	How to analyze the text to understand the text?

E1) problems are unique
E2) solutions for the problem will be unique

E3) requirements are unique
E4) solution for the requirement will be unique

E5) Decision process will be universal (common sense)
----------------------------------------
6)	What is the universal decision process?

Decision process, is looking for;
F1) problem
F2) requirement
----------
F3) solution
----------
F4) path that leads for problem
F5) path that leads for requirement
F6) path that leads for solution

considering the above inputs , i would like to see the text ,analyze them and understand them as per point 6, and find the main word using parsers(grammar)

_Originally posted by @Shasetty in https://github.com/ufal/udpipe/issues/177#issuecomment-1793277375_

**Comment by arademaker** [comment]
Dear @Shasetty, please don't take me wrong, but I assume you don't have the necessary background to understand why #177 was closed. 

Natural Language Processing is a massive area, including many different tasks. Given a piece of text, we usually understand that many steps must be done to transform text (a blog of symbols in a computer) to a representation that some application can manipulate or use directly.  Here is a list of excellent textbooks that can help you be introduced to the area:

1. https://web.stanford.edu/~jurafsky/slp3/
2. https://www.amazon.com/Natural-Language-Understanding-James-Allen/dp/0805303340
3. https://www.amazon.com/Linguistic-Fundamentals-Natural-Language-Processing/dp/1681736713
4. https://www.amazon.com/Linguistic-Fundamentals-Natural-Language-Processing/dp/1681736713

To make a long story short. We don't do everything in one step. The repository here is about a statistical parser, a tool designed to take a string and produce a data structure representing one particular syntactic analysis in the theory of http://universaldependencies.org. UDPipe can already do too much: tokenization, segmentation into sentences, morphosyntactic analysis of the words, and parsing (syntactic analysis). By construction, these are the functionalities of UDPipe.

Other tools can take the output of UDPipe to produce further representations of semantics — for example, https://github.com/sivareddyg/UDepLambda. Indeed, we know that semantics can contribute to syntactic... see more in Allen's book above. However, UDPipe is not implemented in this approach of language processing. 

So please, this is not an issue for this repository. You are not reporting a bug. You are not making a reasonable request for features. Please educate yourself in the area. Use other internet forums to discuss ideas for projects.

**Comment by foxik** [comment]
@arademaker Thank you very much for a very nice response! :heart:
