### ISSUE TITLE
Cannot obtain the list of models from the service.

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#179]
I tried to use 
https://lindat.mff.cuni.cz/services/udpipe/ 

it says 
Cannot obtain the list of models from the service.

what should be done?
can you pleas inform.

**Comment by martinpopel** [comment]
The UDPipe backend server is currently down as reported at https://lindat.mff.cuni.cz/en/monitoring. There is nothing you can do, just wait until the Lindat team fixes it (I have notified them, but they were already notified by the Monitoring Dashboard).

**Comment by Shasetty** [comment]
Thank you

**Comment by foxik** [comment]
Sorry, that was my mistake introduced in 4173a5b09 and fixed by 25549ab01; it now works again.
