### ISSUE TITLE
Installing UDPipe2 on local machine

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#180]
I tried to install UDPipe 2 locally, on my machine,
with the help of different python programmers.
(I am a non programmer).

No python programmer was able to install them.

Can any of you install UDPipe 2 locally on my machine
or
suggest some body, who can install it.

If you do this to me, It would be of great help to me.

Thanks in advance

Regards
Shankar

**Comment by foxik** [comment]
The installation instructions are described on https://github.com/ufal/udpipe/tree/udpipe-2, so try following them. We generally do not have resources to provide user support, so if you do not know how to perform the individual steps, try asking on stackoverflow or similar places. However, if you encounter problems where UDPipe does not work correctly (i.e., there is a bug in UDPipe), then report it here (what you did, what should happen, what happen instead, including error logs, etc), and we will fix it in UDPipe.
