### ISSUE TITLE
Unable to install UDPipe 2 as a local REST server,

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#183]
Requirements installed:

tensorflow_gpu~=2.10.1 
ufal.chu_liu_edmonds
ufal.udpipe>=1.3,<2
----------------------------------------

error while installing wembeddings 

command: pip3 install -r requirements.txt, 
        python3 ./start_ wembeddings_server.py 8000

[UDPIPE.docx](https://github.com/ufal/udpipe/files/13768951/UDPIPE.docx)

------------------------------------------------------------
Please help me in installing.

**Comment by foxik** [comment]
Please, next time attach the textual logs, not an image.

The attached error message is not complete, so it is hard to tell, but it seems your environment has some package version mismatch. I would remove the Python virtual environment and reinstall it.
- Do you want just to run inference? If so, you can have just a single virtual environment, which should contain the packages `tensorflow ufal.chu_liu_edmonds ufal.udpipe>=1.3,<2 transformers>=4,<5`.
- If you want to also train UDPipe 2, you will need two environments (one for UDPipe 2 and the other one for wembedding server, each with the packages from the corresponding `requirements.txt` file).
