### ISSUE TITLE
confusion in UD 2.12 and UD 2.10 (Which one should be followed by non-experts in Grammar? )

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#185]
There are lot of structural changes on the parent & child relationship between version 2.10 & 2.12.
-------------------------------------------------------------------
1)Which version is the correct one? 
2)Which version should be followed by non-experts in Grammar?
-------------------------------------------------------------------
Text:
The Unregistered Warrants and the Unregistered Warrant Shares are not being registered under the Securities Act of 1933, as amended (the “Securities Act”), pursuant to the registration statement of which this prospectus supplement and the accompanying base prospectus form a part and are not being offered pursuant to this prospectus supplement and the accompanying base prospectus.

acl(Act-16,amended-21) : version ud 2.10-220711

advcl(registered-12,amended-21) : version 2.12.230717

-------------------------------------------------------------------

**Comment by Shasetty** [comment]
english ewt ud 2.12-230717
english ewt ud 2.10-220711.

i used above  corpus for getting the output in parsers.

**Comment by foxik** [comment]
Hi, the parser models are machine learning models, so they do not produce 100% valid output.
- For the UD 2.10 model, LAS (accuracy of correctly predicted dependency edges plus relations) on `en-ewt` is 83.2% according to https://ufal.mff.cuni.cz/udpipe/2/models#universal_dependencies_210_models
- For the UD 2.12 model, LAS on `en_ewt` is 91.0% according to https://ufal.mff.cuni.cz/udpipe/2/models#universal_dependencies_212_models

So they predict only 4 out of 5 (UD 2.12) or 9 out of 10 (UD 2.12) edges correctly on the test data; on the real-world data, the score will be even lower. If you want to get 100% correct output, you will need to manually post-process the predictions (or find someone to do it).
