### ISSUE TITLE
I confirm the right brackets following FDA and NDA are attached to a wrong parent (i.e. not to FDA and NDA, respectively), when parsing this very long sentence with english-ewt-ud-2.12-230717. You can use [udapy -s ud.FixPunct < in.conllu > out.conllu](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py) to fix it.

### ISSUE THREAD

**Issue by Shasetty** [ufal/udpipe#187]
I confirm the right brackets following FDA and NDA are attached to a wrong parent (i.e. not to FDA and NDA, respectively), when parsing this very long sentence with english-ewt-ud-2.12-230717. You can use [udapy -s ud.FixPunct < in.conllu > out.conllu](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py) to fix it.

However, the output in "Show Trees" is exactly the same as in "Show Table" (and as the CoNLL-U in "Output Text"), so there is no bug in UDPipe. These GitHub issues are for reporting bugs in the software. You cannot expect 100% parsing accuracy from all models.

BTW: When using e.g. the english-gum-ud-2.12-230717 model, the brackets enclosing FDA and NDA are attached correctly. This suggest GUM is better training data then EWT in this aspect. Indeed, when applying `ud.FixPunct` on en_gum-ud-train.conllu, there are only 39 errors fixed, but on en_ewt-ud-train.conllu, there are 7496 bugs. So maybe the authors of EWT should fix these bugs and the new version of UDPipe will be better. However, that should not be discussed here, but at https://github.com/UniversalDependencies/UD_English-EWT/issues

_Originally posted by @martinpopel in https://github.com/ufal/udpipe/issues/175#issuecomment-1768050976_

**Comment by Shasetty** [comment]
i am using "english-ewt-ud-2.10-220711" can i use the [udapy -s ud.FixPunct < in.conllu > out.conllu] to fix the text and bracket errors.

**Comment by foxik** [comment]
This seems to be a question about udapy, i.e., unrelated to UDPipe, so closing the issue.
