### ISSUE TITLE
method to plug a morpological dictionary

### ISSUE THREAD

**Issue by nittti** [ufal/udpipe#22]
As pretty much everybody who opens an issue here, I want to thank you for such a great (out-of-the-box great!) tool.

UDPipe section of UD tools [page](http://universaldependencies.org/tools.html) says it is possible to provide a morphological dictionary. Could you please describe how can that be done? There is a lexicon of form-lemma-upos-ufeat format.

**Comment by foxik** [comment]
In UDPipe 1.1, the dictionary can be plugged in using ``dictionary`` option of a tagger, see https://ufal.mff.cuni.cz/udpipe/users-manual#model_training_tagger .
