### ISSUE TITLE
create binary wheels for windows (Appveyor, macOS and manylinux1 (tavis)

### ISSUE THREAD

**Issue by graingert** [ufal/udpipe#23]
Followup to https://github.com/ufal/udpipe/issues/8#issuecomment-283129498

There are some pretty easy to follow guides on how to setup appveyor and travis to build wheels:

Windows: https://packaging.python.org/appveyor/#automatically-uploading-wheels
Linux: travis https://github.com/pypa/python-manylinux-demo
macOS: travis https://github.com/MacPython/wiki/wiki/Wheel-building

**Comment by foxik** [comment]
Moved to UDPipe 2.0 milestone.

**Comment by foxik** [comment]
We how have official Windows/Linux/OS X binary wheels.
