### ISSUE TITLE
Building parser models using GPUs

### ISSUE THREAD

**Issue by vin-ivar** [ufal/udpipe#26]
Is it possible to speed up the model building (for the parser) in UDPipe using GPU clusters? I can't seem to find anything that mentions this in the UDPipe or Parsito manuals.

**Comment by foxik** [comment]
That is not currently supported. We plan to add such feature in UDPipe 2.0 targetted for Q3 of 2017 (by using C++ TensorFlow library).

**Comment by foxik** [comment]
Reopening with UDPipe 2.0 milestone.

**Comment by foxik** [comment]
Changing milestone to UDPipe 3.0. In UDPipe 2.0, we are planning only inference using GPU; training will be added in UDPipe 3.0.

**Comment by foxik** [comment]
Closing, as instead of UDPipe 3.0, we will have LinPipe.
