### ISSUE TITLE
how to prevent sentence detection for tokenaztion?

### ISSUE THREAD

**Issue by rasoolims** [ufal/udpipe#30]
Hi, 
I was not able to find any option to turn off sentence delimitation for tokenization. My data needs to be with the same number of sentences after tokenization but UDPIPE separates some of the sentences.
Thanks

**Comment by martinpopel** [comment]
In the new version (to be released very soon), there should be a special input format for sentence-segmented but untokenized input (one sentence per line), I believe.

In the current version v1.0.0, you have to use a [workaround](https://github.com/ufal/udpipe/pull/4/commits/760d4c5fd35feaa1a2fe7e50b093de2a4873cd4d) where you merge together the extra-split sentences (or maybe [input_format_presegmented_tokenizer](https://github.com/ufal/udpipe/blob/5b1b8908f252adad38f772e1eb7a78fbccc4afd2/src/sentence/input_format.cpp#L272), but I am not sure how to use it).

**Comment by rasoolims** [comment]
What should be the path for PERL_INCLUDE? I tried different paths to install Perl bindings but was not successful.

**Comment by martinpopel** [comment]
If you need the Perl binding, install it from [CPAN](https://metacpan.org/pod/Ufal::UDPipe), e.g. with `cpanm Ufal::UDPipe`.
The workaround I referenced can be easily done in any other of the supported programming languages.

That said, I would suggest to wait for the new release.
It will published soon and the new models for this release were already [published](https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1990).

**Comment by foxik** [comment]
As @martinpopel said, tokenizer respecting given segmentation will be present in UDPipe 1.1.

As for PERL_INCLUDE, if you prefer to compile the bindings manually instead of using cpan, PERL_INCLUDE should point to a directory containing `perl.h`, as the Makefile suggests. On my machine it is at `/usr/lib/x86_64-linux-gnu/perl/5.20/CORE`.

**Comment by rasoolims** [comment]
I found a hacky way to do this by changing [this line](https://github.com/ufal/udpipe/blob/master/src/model/model_morphodita_parsito.cpp#L33) to the following:

```c++
return input_format::new_presegmented_tokenizer(result);
```

**Comment by foxik** [comment]
This is what the new code does (but in a configurable way :-), see https://github.com/ufal/udpipe/blob/pre1.1/src/model/model_morphodita_parsito.cpp#L37 .

**Comment by foxik** [comment]
The UDPipe 1.1 is out, with ``presegmented`` tokenizer option respecting input segmentation (documented at https://ufal.mff.cuni.cz/udpipe/users-manual#run_udpipe_tokenizer).
