### ISSUE TITLE
pre-trained models for UD 2.0 doesn't work

### ISSUE THREAD

**Issue by cesarboucas** [ufal/udpipe#33]
First congratulations for this amazing work and thanks for sharing it with us. Bellow I explain the issue I am facing.

When I run the pre-trained models from [udpipe-ud-1.2-160523](https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1659) it works fine. The execution starts after the command:

`./udpipe --tokenize --tag --parse english-ud-1.2-160523.udpipe en-ud-dev.conllu `

But when I try to run a pre-trained model from [udpipe-ud-2.0-conll17-170315](https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1990). I get an error:

`./udpipe --tokenize --tag --parse english-ud-2.0-conll17-170315.udpipe en-ud-dev.conllu
Loading UDPipe model: Cannot load UDPipe model 'english-ud-2.0-conll17-170315.udpipe'!
`

Note that I have confirmed that the english-ud-2.0-conll17-170315.udpipe file is in the folder:

`UDPipe/git/udpipe/src$ ls
common.h                                     Makefile.builtem    sentence
english-partut-ud-2.0-conll17-170315.udpipe  Makefile.include    tokenizer
english-ud-1.2-160523.udpipe                 model               trainer
english-ud-2.0-conll17-170315.udpipe         model.output        udpipe
en-ud-dev.conllu                             morphodita          udpipe.cpp
en-ud-dev.txt                                parsito             unilib
libudpipe.a                                  pt-ud-train.conllu  utils
Makefile                                     rest_server         version
`

Any ideas?

**Comment by foxik** [comment]
Which version of UDPipe are you using? As mentioned in the CoNLL-U baseline models, they require UDPipe 1.1 (released only 3 days ago).

**Comment by cesarboucas** [comment]
Nevermind, did a git pull and now its working.
Thanks
