### ISSUE TITLE
method to plug a morpological guesser 

### ISSUE THREAD

**Issue by nittti** [ufal/udpipe#34]
UDPipe 1.1 made it possible to use a morphological dictionary, which dramatically improves accuracy. To improve even further, is there an "official" way to plug a custom rule-based morphological guesser? (which itself uses dict internally to provide possible interpretations at runtime)
Both external and compile-in solutions are interesting.

**Comment by arademaker** [comment]
Hi, 

I am having bad performance with a corpus from a technical domain that contains many names and MWE from the domain.  Is it possible to supply a dictionary for names and MWE with the goal to improve the tagger and the parser? 

The tagger options described in http://ufal.mff.cuni.cz/udpipe/users-manual#model_training_tagger can also be using during parsing time or only during training time?

**Comment by foxik** [comment]
Currently the options can be used only during training time. You are right that in theory morphological dictionary could be extended at parsing time, but that is not allowed by the current implementation.

**Comment by arademaker** [comment]
Hi @foxik , the option that you gave in https://github.com/ufal/udpipe/issues/7#issuecomment-243210062 is still possible? I mean, the two steps call rewriting the POS tags before the parsing ?

**Comment by foxik** [comment]
The mentioned comment was just a discussion of ideas -- it does not work automatically. The only way how it would work currently is that you would tag the sentence (either through the API or udpipe binary with --tag), then *manually* fix the problematic tags & lemmas, and then parse the sentence.

**Comment by foxik** [comment]
Closing. I doubt we will have an official API for morphological guesser any time soon; the possibility of passing a morphological dictionary at inference time is tracked by #50.
