### ISSUE TITLE
Allow using dictionary_file= to pass dictionary

### ISSUE THREAD

**Issue by ftyers** [ufal/udpipe#36]
At the moment `embedding_form_file=FILENAME` is used to pass embeddings, but to pass a dictionary, you need `dictionary_file=file:FILENAME`. This is inconsistent and could be confusing to users, especially if no error messages are thrown. Could we make `embedding_form_file=file:FILENAME` or `dictionary_file=FILENAME` to be consistent?

**Comment by foxik** [comment]
Sorry if I did not make it clear -- the `dictionary_file` mentioned in #35 will use the `dictionary_file=FILENAME` syntax (instead of current `dictionary=file:FILEAME`).

Leaving open until I fix it (probably sometimes next week).
