### ISSUE TITLE
Documentation tidying

### ISSUE THREAD

**Issue by martinpopel** [ufal/udpipe#39]
The sections 3.2. License and 3.3. Platforms and Requirements
at http://ufal.mff.cuni.cz/udpipe are redundant,
because most of the sentences are already mentioned before.

The almost-empty sections 2.1. Online Demo and 2.2. Web Service are visually strange.
I would suggest just one section "2. Online Demo and Web Service"
and add few more sentences, e.g.
The service is freely available for testing / non-commercial...
REST API...

I was afraid to fix this myself, as there may be reasons behind the duplicity and/or links to those sections from outside.

Feel free to dismiss this issue.

**Comment by foxik** [comment]
I decided to keep the license, but I removed the Platforms and Requirements.

I also tried to improve the Online section in c253f6aa.
