### ISSUE TITLE
R package made available

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#42]
FYI, I've made this R wrapper for udpipe available at https://github.com/bnosac/udpipe

**Comment by foxik** [comment]
Thanks, I have added a link to the README and to the web pages.

Leaving this open for some time as an announcement.

**Comment by jwijffels** [comment]
Thanks. FYI. The package has now also been released on CRAN: https://CRAN.R-project.org/package=udpipe. Feel free to use that link instead.

**Comment by foxik** [comment]
OK, modified.
