### ISSUE TITLE
error: expected primary-expression before ‘enum’ in tokenizer/multiword_splitter.cpp

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#43]
Hi,

The CRAN build farm which is now checking on the udpipe R package (https://cran.r-project.org/web/checks/check_results_udpipe.html) gives an error when building on Solaris: 
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/udpipe-00install.html

This looks like a syntax error in tokenizer/multiword_splitter.cpp
How can this be fixed in ufal/udpipe?

```
* installing to library ‘/home/ripley/R/Lib32’
* installing *source* package ‘udpipe’ ...
** package ‘udpipe’ successfully unpacked and MD5 sums checked
** libs
/opt/csw//bin/g++ -std=gnu++11 -I/home/ripley/R/gcc/include -DNDEBUG  -I"/home/ripley/R/Lib32/Rcpp/include" -I/opt/csw/include -I/usr/local/include   -fPIC  -O2 -c RcppExports.cpp -o RcppExports.o
/opt/csw//bin/g++ -std=gnu++11 -I/home/ripley/R/gcc/include -DNDEBUG  -I"/home/ripley/R/Lib32/Rcpp/include" -I/opt/csw/include -I/usr/local/include   -fPIC  -O2 -c rcpp_udpipe.cpp -o rcpp_udpipe.o
/opt/csw//bin/g++ -std=gnu++11 -I/home/ripley/R/gcc/include -DNDEBUG  -I"/home/ripley/R/Lib32/Rcpp/include" -I/opt/csw/include -I/usr/local/include   -fPIC  -O2 -c udpipe.cpp -o udpipe.o
udpipe.cpp: In member function ‘void ufal::udpipe::multiword_splitter::append_token(ufal::udpipe::utils::string_piece, ufal::udpipe::utils::string_piece, ufal::udpipe::sentence&) const’:
udpipe.cpp:19769:3: error: expected primary-expression before ‘enum’
   enum { UC_FIRST, UC_ALL, OTHER } casing = OTHER;
   ^
udpipe.cpp:19769:36: error: ‘casing’ was not declared in this scope
   enum { UC_FIRST, UC_ALL, OTHER } casing = OTHER;
                                    ^
udpipe.cpp:19769:45: error: ‘OTHER’ was not declared in this scope
   enum { UC_FIRST, UC_ALL, OTHER } casing = OTHER;
                                             ^
*** Error code 1
make: Fatal error: Command failed for target `udpipe.o'
Current working directory /tmp/RtmpyRaOvb/R.INSTALL2ad75272872/udpipe/src
ERROR: compilation failed for package ‘udpipe’
* removing ‘/home/ripley/R/Lib32/udpipe’

real       40.8
user       37.6
sys         2.4

```

**Comment by jwijffels** [comment]
Maybe something like this should be in tokenizer/multiword_splitter.cpp?

```
enum casingtype{ UC_FIRST, UC_ALL, OTHER };
casingtype casing = OTHER;
```

**Comment by foxik** [comment]
Hi, the `enum { UC_FIRST, UC_ALL, OTHER } casing = OTHER;` should be perfectly fine (even in c++03).

I have no access to a Solaris machine -- if you can, could you try using
```
enum { UC_FIRST, UC_ALL, OTHER }; int casing = OTHER;
```
to verify the problem is in the `enum` statement? The problem could be already somewhere above the `enum` statement, with the `enum` being reported falsely.

**Comment by jwijffels** [comment]
The package builds fine on clang, gcc & llvm. Solaris is always a bit more picky in the C++ conventions.

Thanks for the propose solution! I also don't have access to a Solaris machine. But it is provided as part of the [r-hub](https://github.com/r-hub/rhub) 

Running this with the modification ` enum { UC_FIRST, UC_ALL, OTHER }; int casing = OTHER;` already solves that compilation issue on Solaris.

```
library(rhub)
check(platform = "solaris-x86-patched")
```

But another one pops up. I'll open up a new issue on that.
