### ISSUE TITLE
udpipe_server

### ISSUE THREAD

**Issue by gcelano** [ufal/udpipe#48]
I am trying to start the server with the command:

udpipe_server 8080 /path-to-the-model/udmodel.udpipe

but I get the message "Cannot load specified models!"

What am I missing?

**Comment by foxik** [comment]
The second argument is just a name of the default model; each model has to be specified using three arguments -- name, filepath and acknowledgements. So use
`
updipe_server 8080 some_name some_name filepath ""
`
