### ISSUE TITLE
Allow additional external morphological dictionary during inference.

### ISSUE THREAD

**Issue by foxik** [ufal/udpipe#50]
In addition to the "internal" morphological dictionary stored in the model, it would make sense to allow using additional external dictionary during tagging only.

**Comment by ftyers** [comment]
While making it, it would be cool if there could be some kind of functionality in the API that would allow people to call external (weighted) morphological analysers (for example for languages for which creating a full-form list is problematic because of morphological/orthographical processes).

**Comment by foxik** [comment]
I agree that that would definitely be useful, but I do currently have other priorities. But I am open to accept patches :-)

Note that there is a lot of design space here -- either allowing a morphological dictionary as a list, allowing ATT, allowing any binary call, or allowing the morphological analysis to be part of input (for example using a sentence-level comment)... Additionally, instead of words, multi-word tokens could also be supported.
