### ISSUE TITLE
Differences in accuracies between MacOS and Linux binaries

### ISSUE THREAD

**Issue by nishkalavallabhi** [ufal/udpipe#51]
There seems to be a lot of difference between the POS tagging output on MacOS and Linux. Did anyone else experience this? I am attaching the screenshots of Version 1.2 Binaries, but this issue remained even when I compiled from the source repo, and with 1.1 version binaries.

![udpipe-1 2-linux](https://user-images.githubusercontent.com/7221440/32625167-29f484f8-c551-11e7-8b33-27f3f77e8be5.png)
![udpipe-1 2-macos](https://user-images.githubusercontent.com/7221440/32625200-409f1ac4-c551-11e7-9922-968f7fb19710.png)

**Comment by foxik** [comment]
Thanks for telling us! I do not use OS X myself, which is why I did not notice this before.

I will try looking into it as soon as possible, but I am currently on a research stay abroad, which leaves me less time for UDPipe.

**Comment by foxik** [comment]
BTW, the bug has been fixed in master for quite some time -- the problem was fixed by 9dee3979a4899 in Nov 22 2017. However, we still did not have a release since -- I will make it in upcoming weeks (together with binary wheels for all platforms).
