### ISSUE TITLE
colon vs semi-colon in user manual documentation

### ISSUE THREAD

**Issue by nishkalavallabhi** [ufal/udpipe#60]
In the UDPipe Manual, Section 1.3, there is this sentence:
"If the --tokenize option is supplied, the input is assumed to be plain text and is tokenized using model tokenizer. Additional arguments to the tokenizer might be specified using --tokenizer=data option (which implies --tokenize), where data is a semicolon-separated list of the following options "
-I think it is not semicolon separated. Semi-colon separated options seems to throw me an error, whereas colon separated options works fine.

**Comment by foxik** [comment]
It really is semicolon, see https://github.com/ufal/udpipe/blob/master/src/utils/named_values.h#L53. But beware that your shell probably interprets semicolon as a command separator -- you need to escape it.
