### ISSUE TITLE
Minimum working example for Python

### ISSUE THREAD

**Issue by ajdapretnar** [ufal/udpipe#61]
This looks like a great tool, but I am struggling to get it working with Python. Could you provide a minimum working example?

I imagine sth like:
```
from ufal.udpipe import Tokenizer

data = open("mydata")
tokenize = Tokenizer()
new_data = tokenize(data)
print(new_data[:3])
```

**Comment by martinpopel** [comment]
See https://github.com/ufal/udpipe/blob/master/releases/pypi/test/test_udpipe.py and https://pypi.python.org/pypi/ufal.udpipe/1.2.0.1#run-udpipe

**Comment by ajdapretnar** [comment]
Thank you!
