### ISSUE TITLE
Way to represent different tokenisations in dictionary format

### ISSUE THREAD

**Issue by ftyers** [ufal/udpipe#63]
In addition to being able to use a morphological analyser/dictionary during inference (#50) it would be cool if the dictionary format allowed for multi-word surface tokens, for example:

```
15-17   arreglándotelo  _       _       _       _       _       _       _       SpaceAfter=No
15      arreglándo      arreglar        VERB    _       VerbForm=Ger    12      acl     _       _
16      te      tú      PRON    _       Case=Acc,Dat|Number=Sing|Person=2|PrepCase=Npr|PronType=Prs     15      iobj    _       _
17      lo      él      PRON    _       Case=Acc|Gender=Masc|Number=Sing|Person=3|PrepCase=Npr|PronType=Prs     15      obj     _       _
```

At the moment this does not seem to be possible in the dictionary format:

```dictionary_file (default empty): use a given custom morphological dictionary, where each line contains 5 tab-separated fields FORM, LEMMA, UPOSTAG, XPOSTAG and FEATS. Note that this dictionary data is appended to the dictionary created from the UD training data, not replacing it. ```

**Comment by ftyers** [comment]
Note that the FST-based approach outlined in #50 could take care of this fairly easily.

**Comment by foxik** [comment]
I agree that that would definitely be useful, but I do currently have other priorities. But I am open to accept patches :-)

**Comment by foxik** [comment]
Closing, as future development will move from UDPipe to LinPipe.
