### ISSUE TITLE
make bindings/csharp error

### ISSUE THREAD

**Issue by notesjor** [ufal/udpipe#66]
If I run make in bindings/csharp, I recived the following error message:

swig -O -c++ -outcurrentdir -csharp -namespace Ufal.UDPipe -outdir Ufal\UDPipe -o udpipe_csharp.cpp udpipe_csharp.i
process_begin: CreateProcess(NULL, swig -O -c++ -outcurrentdir -csharp -namespace Ufal.UDPipe -outdir Ufal\UDPipe -o udpipe_csharp.cpp udpipe_csharp.i, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [Makefile:25: udpipe_csharp.cpp] Error 2

**Comment by notesjor** [comment]
reason: bindings/csharp/.gitignore includes udpipe_csharp.cpp

**Comment by foxik** [comment]
The Makefile tries to generate udpipe_csharp.cpp using swig, which you do not have installed (which is what the "CreateProcess failed" means).

Either install swig, or use the precompiled bindings -- all binary releases here on Github contains precompiled C# bindings for Linux/Win/OS X 32/64.
