### ISSUE TITLE
bin-win64 contains a 32-bit DLL (udpipe_csharp.dll)

### ISSUE THREAD

**Issue by notesjor** [ufal/udpipe#67]
The current release contains a 32-bit version of \bin-win64\csharp\udpipe_csharp.dll
A 64-bit version would allow a C# assembly to run in 64-bit mode (which has some advantages - e.g. larger memory limit).

**Comment by foxik** [comment]
Why do you think the bin-win64/csharp/udpipe_csharp.dll is 32-bit? The latest (1.2.0) is identified as pei-x86-64 DLL, and the disassembler is showing 64bit code.

**Comment by notesjor** [comment]
After a few tests with SWIG and a few changed configurations, I can now load the DLL. But in the end the main mistake was on my side. It always takes some time to understand the source code of others and use PInvoke right. Thank you very much for your help.
