### ISSUE TITLE
REST API file size limitations

### ISSUE THREAD

**Issue by Henry-E** [ufal/udpipe#68]
What are the limitations on file size for the udpipe REST API? I'm getting a "Request was too large." error

Are there any other caps on usage. For example as a workaround if the text file was sent in smaller chunks would that be ok.

[ I posted the same [issue](https://github.com/CoNLL-UD-2017/UFAL-UDPipe-1.2/issues/2) on the other udpipe repo, which is where google led me when searching for "request was too large". This repo seems much busier though so reposting here.]

**Comment by Henry-E** [comment]
Converting the text files to smaller chunks seems to be working well. If it does ever seem like I'm abusing the API please feel free to get in touch.

**Comment by foxik** [comment]
As per https://github.com/ufal/udpipe/blob/master/src/rest_server/udpipe_server.cpp#L125, the limit on the size of the POST request is 1MB. The reason for the limit is to make sure we do not run out of RAM on the machine.

If you have larger documents, you can either:
- split it into smaller chunks (which is what you did)
- or download the udpipe binary and models and run locally

Cheers,
Milan

**Comment by Henry-E** [comment]
Thanks for providing such a useful service! It seemed like a much easier approach to use the rest api than getting all the binary and models running localling when I'm not going to be using it that extensively.
