### ISSUE TITLE
grep: log/log.test.raw: No such file or directory

### ISSUE THREAD

**Issue by mjj1094** [ufal/udpipe#70]
After I ran the "sh ./result_table.sh ,  The following error message is displayed on the screen：
(branch:master model:models-ud-2.0 language:zh(Chinese))
grep: ../ud-2.0/log/log-ud-test.conllu: No such file or directory
grep: ../ud-2.0/log/log-ud-test.conllu: No such file or directory
grep: ../ud-2.0/log/log-ud-test.conllu: No such file or directory
grep: log/log.test.raw: No such file or directory
grep: log/log.test.raw: No such file or directory
grep: log/log.test.raw: No such file or directory
grep: log/log.test.raw: No such file or directory
grep: log/log.test.raw: No such file or directory
grep: log/log.test.goldtok: No such file or directory
grep: log/log.test.goldtok: No such file or directory
grep: log/log.test.goldtok: No such file or directory
grep: log/log.test.goldtok: No such file or directory
grep: log/log.test.goldtok: No such file or directory
grep: log/log.test.goldpos: No such file or directory
grep: log/log.test.goldpos: No such file or directory
grep: log/log.test.goldpos: No such file or directory
grep: log/log.test.goldpos: No such file or directory
grep: log/log.test.goldpos: No such file or directory

 |                      | Raw text       |    -   |    -   |   -   |   -   |    -   |     -   |    -   |   -   |   -   |
 |                      | Gold tok       |    -   |    -   |   -   |   -   |    -   |     -   |    -   |   -   |   -   |
 |                      | Gold tok+morph |    -   |    -   |   -   |   -   |    -   |     -   |    -   |   -   |   -   |
 | Chinese              | Raw text       |  90.2% |  98.8% | 84.0% | 83.8% |  89.0% |   82.7% |  90.2% | 62.6% | 58.4% |
 | Chinese              | Gold tok       |    -   |    -   | 92.2% | 92.0% |  98.7% |   90.8% | 100.0% | 75.9% | 70.5% |
 | Chinese              | Gold tok+morph |    -   |    -   |   -   |   -   |    -   |     -   |    -   | 84.3% | 81.5% |

However, there are some results In the last few lines.

Looking forward to your reply！ Thank you！

**Comment by foxik** [comment]
The script generates results for UDPipe documentation, and it uses all subdirectories as models to print. It seems you created a `log` directory, which is why you get so many errors (as it does not contain the logs with results, neither does test data for the language 'log' exist).

The script is generally an internal formatting script, which you are of course free to use, but we provide no support for it.
