### ISSUE TITLE
An error occurred during model training: Not enough training data for the gru_tokenizer!

### ISSUE THREAD

**Issue by KatyaAplonova** [ufal/udpipe#75]
I can not train a model on my data ([An error occurred during model training: Not enough training data for the gru_tokenizer!], even it has 13234 tokens, which seems to be enough for training. Training conllu files are here: https://github.com/KatyaAplonova/UD_Bambara/tree/master/conllu

**Comment by foxik** [comment]
Could you elaborate on the UDPipe version and the command used? I am trying UDPipe 1.2 and training command
```
udpipe --train bambara.model conllu/*.conllu
```
starts tokenizer training without any problem.
