### ISSUE TITLE
"english-ud-2.0-170801.udpipe" not available

### ISSUE THREAD

**Issue by shashankgjoshi** [ufal/udpipe#77]
The above is not available after installing udpipe. How to go about it? Thanks

**Comment by shashankgjoshi** [comment]
Sorry not been able to figure out exactly what is to be done. Have installed udpipe in Rstudio 3.5.1. It is now giving error that the above file for English is not found. Can you help with some more details? Thanks

**Comment by foxik** [comment]
You need to download model for English, it is not downloaded automatically. All UD 2.0 models can be downloaded from http://hdl.handle.net/11234/1-2364 .
