### ISSUE TITLE
Spaces in MISC

### ISSUE THREAD

**Issue by msklvsk** [ufal/udpipe#87]
Since spaces are allowed in `FORM`, should they be allowed in `MISC`? e.g. for `Translit` and `Gloss` fields.

I added this in `input_format.cpp` and it works:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/473012/48337737-75158080-e66c-11e8-9d13-b3d88d038138.png">

**Comment by foxik** [comment]
We are discussing allowing the space oficially in the CoNLL-U v2 specification
https://github.com/UniversalDependencies/docs/issues/588. I also pushed the change to UDPipe in 60e2288, but it may get reverted if we decide not to allow spaces (but I think it is unlikely).
