### ISSUE TITLE
Python example doesn't work

### ISSUE THREAD

**Issue by evanmiltenburg** [ufal/udpipe#9]
The method `finishDocument()` doesn't exist, so the Python example doesn't work. 
[This line](https://github.com/ufal/udpipe/blob/master/bindings/python/examples/udpipe_model.py#L62) needs to be removed.

**Comment by foxik** [comment]
The method has been in UDPipe since commit 34e9575 (the Python example is indeed working for me, using current HEAD).

But you are right that the last stable version does not have the method -- however, both the `stable` branch and the PyPI package do not include the `udpipe_model.py` example.
