### ISSUE TITLE
collocation function

### ISSUE THREAD

**Issue by heyitsbrad** [ufal/udpipe#91]
The collocation function doesn't give an option to retrieve doc_id's.

doc_id's are needed to create a DTM from collocations with single words for the purpose of document similarity calculations.

**Comment by jwijffels** [comment]
There is no collocation function in the UDPipe C++ library, only in the udpipe R package. Please put questions or issues regarding the R package on 
https://github.com/bnosac/udpipe

**Comment by foxik** [comment]
Thanks @jwijffels for the answer.
