### ISSUE TITLE
Difference between UD 2.0 and UD 2.3

### ISSUE THREAD

**Issue by Henry-E** [ufal/udpipe#92]
Apologies for the naive question but what is the difference between UD 2.0 and 2.3? There doesn't seem to any clear information on this except on the different update logs of the various treebanks, where it appears to be mostly improvements to the annotations. 

I have a program that was designed to work with / process the output of a UD 2.0 parser, is there any reason why it wouldn't work the same with 2.3? The program is running fine with 2.3 output currently but this question is just to make sure there's no hidden bugs I'm missing.

**Comment by martinpopel** [comment]
Yes, the difference between UD 2.0 and 2.3 is in the number of treebanks (and languages) included, in the amount of sentences in some treebanks and in the quality of annotation. There were no (major) changes in the UD guidelines and the CoNLL-U format (such changes can happen only in major UD versions, e.g. UD 2 -> UD 3).

> output of a UD 2.0 parser

As you are asking here, I guess you mean the UDPipe parser with models trained on UD 2.0.  Your program should work with the output of UDPipe with UD 2.3 models, but if your program contains any component *trained* on UD 2.0*, you may get better results by re-training it on UD 2.3.

**Comment by Henry-E** [comment]
Excellent. Fortunately this is a rule based program so this shouldn't be an issue. Thanks very much!
