### ISSUE TITLE
issue in installing "pip install ufal.morphodita"

### ISSUE THREAD

**Issue by binsypillai** [ufal/udpipe#93]
hi all i am getting error while running pip install ufal.morphodita==1.9.2.1.

Collecting ufal.morphodita
  Using cached https://files.pythonhosted.org/packages/40/80/f54153a09154e670d68d22ab10caa0ecb3896443b93301f58df6705ebba9/ufal.morphodita-1.9.2.1.tar.gz
Building wheels for collected packages: ufal.morphodita
  Building wheel for ufal.morphodita (setup.py) ... error
  Complete output from command /Users/binsypillai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-install-1sfbfvy3/ufal.morphodita/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-wheel-hp0zl1wv --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/ufal
  copying ufal/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ufal
  copying ufal/morphodita.py -> build/lib.macosx-10.7-x86_64-3.6/ufal
  running build_ext
  building 'ufal_morphodita' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/morphodita
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/binsypillai/anaconda3/include -arch x86_64 -I/Users/binsypillai/anaconda3/include -arch x86_64 -Imorphodita/include -I/Users/binsypillai/anaconda3/include/python3.6m -c morphodita/morphodita.cpp -o build/temp.macosx-10.7-x86_64-3.6/morphodita/morphodita.o -std=c++11 -fvisibility=hidden -w
  morphodita/morphodita.cpp:6:10: fatal error: 'algorithm' file not found
  #include <algorithm>
           ^~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ufal.morphodita
  Running setup.py clean for ufal.morphodita
Failed to build ufal.morphodita
Installing collected packages: ufal.morphodita
  Running setup.py install for ufal.morphodita ... error
    Complete output from command /Users/binsypillai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-install-1sfbfvy3/ufal.morphodita/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-record-h721loo8/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/ufal
    copying ufal/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/ufal
    copying ufal/morphodita.py -> build/lib.macosx-10.7-x86_64-3.6/ufal
    running build_ext
    building 'ufal_morphodita' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/morphodita
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/binsypillai/anaconda3/include -arch x86_64 -I/Users/binsypillai/anaconda3/include -arch x86_64 -Imorphodita/include -I/Users/binsypillai/anaconda3/include/python3.6m -c morphodita/morphodita.cpp -o build/temp.macosx-10.7-x86_64-3.6/morphodita/morphodita.o -std=c++11 -fvisibility=hidden -w
    morphodita/morphodita.cpp:6:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/binsypillai/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-install-1sfbfvy3/ufal.morphodita/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-record-h721loo8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xq/zbmpb6kn2q745zfc3twbkyfw0000gn/T/pip-install-1sfbfvy3/ufal.morphodita/

**Comment by foxik** [comment]
For some reason, your C++ compiler is not functional (it cannot find standard header `algorithm`). In some other project, this was solved by adding `--stdlib=c++` on OS X -- could you try installing from
```
https://ufallab.ms.mff.cuni.cz/~straka/morphodita/ufal.morphodita-1.9.2.2-dev.tar.gz
```
(using `pip install ABOVE_URL`) and report the results?

**Comment by binsypillai** [comment]
it got solved... I upgraded the operating system in my mac bookpro ...
