### ISSUE TITLE
[udpipe-ud-2.3 english-lines] Tokens with upostag ADP have xpostag of underscore rather than IN

### ISSUE THREAD

**Issue by Vimos** [ufal/udpipe#94]
When I am using `udpipe-ud-2.3-181115` and model `english-lines-ud-2.3-181115.udpipe` for tokenization, I find all the tokens with upostag `ADP` have xpostag of '_'.

Command line for the tokenization
```
${UDPIPE_HOME}/src/udpipe --tokenize --tokenizer=presegmented  \
--tag --input format=horizontal \
--parse ${UDPIPE_HOME}/model/udpipe-ud-2.3-181115/english-lines-ud-2.3-181115.udpipe \
 race_qa.txt \
--outfile=race_qa_udpipe.conllu
```
Here is a sample, number 5 `about` has `upostag` of `ADP` but `xpostag` is `_`, but in the tree bank, it should be `IN`.
```
# newdoc id = race_qa.txt
# newpar
# sent_id = 1
# text = What can we know about Cabin Fever?
1	What	what	PRON	WH	PronType=Int	4	obj	_	_
2	can	can	AUX	PRES-AUX	VerbForm=Fin	4	aux	_	_
3	we	we	PRON	PERS-P1PL-NOM	Case=Nom|Number=Plur|Person=1|PronType=Prs	4	nsubj	_	_
4	know	know	VERB	INF	VerbForm=Inf	0	root	_	_
5	about	about	ADP	_	_	6	case	_	_
6	Cabin	cabin	PROPN	SG-NOM	Number=Sing	4	obl	_	_
7	Fever	fever	NOUN	SG-NOM	Number=Sing	6	flat	_	SpaceAfter=No
8	?	?	PUNCT	QuestionMark	_	4	punct	_	SpacesAfter=\n
```

When I am using `english-ewt-ud-2.3-181115.udpipe`, the result is correct.

Can anyone give me a link showing the difference of the two models?
Thank you!

**Comment by jwijffels** [comment]
That is because in the training data that pattern of _ for ADP also happen. See
https://github.com/UniversalDependencies/UD_English-LinES/blob/master/en_lines-ud-test.conllu

**Comment by Vimos** [comment]
So this is due to the training data, got it! 
Thanks!
