### ISSUE TITLE
Structural Topic Model

### ISSUE THREAD

**Issue by SkelAlex** [ufal/udpipe#95]
Hi,
I am doing textual analysis using the STM package and I am wondering exactly how I can get UDPipe (language = french) to be integrated into my STM model. I tried different options but none seems to fit thus far.

I am working with textual data both in French and English and STM identifies relevant topics in English but not in French, since it considers as relevant words determiners like "les", "ses", "des", etc. who are not in practice indicative of topics.

Is UDPipe suited for structural topic modelling? If yes, would it be possible to have an example of how to integrate it?

Thanks a lot,
Alexandre

**Comment by foxik** [comment]
UDPipe performs segmentation, tokenization, POS tagging, morphological analysis, lemmatization and labelled dependency parsing. If you can somehow utilize any of the generated features in STM, then by all means do so :-) But we do not have any examples of using the UDPipe output in downstream tasks.

**Comment by fridrichmrtn** [comment]
Hi @SkelAlex,

you might want to check [this page](https://bnosac.github.io/udpipe/docs/doc6.html). It contains a tutorial on how to leverage `udpipe` with `topicmodels`. It is not far stretched from modeling with `stm`.

Br,

MF

@foxik Thanks for the amazing work you guys are doing on `udpipe`.
