### ISSUE TITLE
Presegmented Tokenizer for Python

### ISSUE THREAD

**Issue by siyanapavlova** [ufal/udpipe#96]
Hi,
I was wondering if there is a way to use the presegmented tokenizer through Python.
Thanks

**Comment by foxik** [comment]
Definitely -- when creating a tokenizer (through `Model.newTokenizer`, unless you use the generic tokenizer), you can pass options (as first argument) -- passing Model.TOKENIZER_PRESEGMENTED gives you a presegmented variant of the tokenizer.

Closing, but feel free to reopen if you have further questions.

**Comment by siyanapavlova** [comment]
Thank you very much for the quick response, it worked :)
