### ISSUE TITLE
dtm_remove_terms: Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by Hadsga** [ufal/udpipe#98]
Hi, 

created a dtm were I removed sparse terms:

```
library(tm)

corpus = Corpus(VectorSource(datsub$Reviews)) 

dtm = DocumentTermMatrix(corpus)

dtm = removeSparseTerms(dtm, 0.98)
```

However, there are still some terms which I want to remove. I try to use your package for this task.

`uselss_terms = c("phone", "just", "really", "day", "month", "now", "blu", "also", "everything", "back", "first", "far", "much", "thing", "iphone", "still", "samsung", "lot", "week", "call", "year", "hour", "never", "way", "many", "star", "enough", "overall", "able", "brand", "however", "even", "product", "mobile", "review", "need")
`
```
library(udpipe)

dtm_remove_terms(dtm, useless_terms)
```

But I get this message:

`Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 'x' must be an array of at least two dimensions
`

**Comment by foxik** [comment]
This concerns the R package https://github.com/bnosac/udpipe, please raise the issue there.
